import { IBM_Plex_Serif, Montserrat } from "@next/font/google";
import "./globals.css";

const ibmPlexSerif = IBM_Plex_Serif({
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
  variable: "--font-ibm-plex-serif",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${ibmPlexSerif.variable} ${montserrat.variable}`}
    >
      <body  className="scroll-smooth" >{children}</body>
    </html>
  );
}
